#ifndef INC_PERIPHERALS_BASE_H_
#define INC_PERIPHERALS_BASE_H_

#include "memlayout.h"

#define MMIO_BASE   (KERNBASE + 0x3F000000)
#define LOCAL_BASE  (KERNBASE + 0x40000000)

#endif  // INC_PERIPHERALS_BASE_H_
